def default_borehole_layout() -> dict:
    return {
        "schemaVersion": 5,
        "mode": "runtime",
        "regions": {
            "left": ["validation-panel", "ai-workflow"],
            "center": ["log-widget"],
            "right": ["interval-details", "curve-catalog"],
        },
        "grid": {
            "columns": 12,
            "rowHeight": 72,
            "items": [
                {"widgetId": "total-depth", "x": 0, "y": 0, "w": 2, "h": 1},
                {"widgetId": "interval-count", "x": 2, "y": 0, "w": 2, "h": 1},
                {"widgetId": "curve-count", "x": 4, "y": 0, "w": 2, "h": 1},
                {"widgetId": "corebox-count", "x": 6, "y": 0, "w": 2, "h": 1},
                {"widgetId": "curve-coverage", "x": 8, "y": 0, "w": 2, "h": 1},
                {"widgetId": "correction-progress", "x": 10, "y": 0, "w": 2, "h": 1},
                {"widgetId": "validation-panel", "x": 0, "y": 1, "w": 2, "h": 4},
                {"widgetId": "ai-workflow", "x": 0, "y": 5, "w": 2, "h": 4},
                {"widgetId": "interpretation-queue", "x": 0, "y": 9, "w": 9, "h": 3},
                {"widgetId": "log-widget", "x": 2, "y": 1, "w": 7, "h": 8},
                {"widgetId": "interval-details", "x": 9, "y": 1, "w": 3, "h": 6},
                {"widgetId": "curve-catalog", "x": 9, "y": 7, "w": 3, "h": 3},
                {"widgetId": "evidence-coverage", "x": 9, "y": 10, "w": 3, "h": 3},
            ],
        },
        "widgets": {
            "total-depth": {
                "type": "singleValue",
                "title": "Total Depth",
                "metric": "total_depth",
                "settings": {"unit": "m"},
            },
            "interval-count": {"type": "singleValue", "title": "Intervals", "metric": "interval_count"},
            "curve-count": {"type": "singleValue", "title": "Curves", "metric": "curve_count"},
            "curve-coverage": {
                "type": "singleValue",
                "title": "Curve Coverage",
                "metric": "curve_coverage_percent",
            },
            "correction-progress": {
                "type": "singleValue",
                "title": "Correction Progress",
                "metric": "corrected_interval_percent",
            },
            "corebox-count": {"type": "singleValue", "title": "Coreboxes", "metric": "corebox_count"},
            "validation-panel": {"type": "validationPanel", "title": "Validation", "settings": {"maxIssues": 8}},
            "interpretation-queue": {
                "type": "interpretationQueue",
                "title": "Interpretation Queue",
                "settings": {"maxItems": 10},
            },
            "ai-workflow": {"type": "aiWorkflow", "title": "AI Workflow", "settings": {"showSummary": True}},
            "interval-details": {
                "type": "intervalDetails",
                "title": "Depth Metadata",
                "settings": {"editable": True},
            },
            "curve-catalog": {
                "type": "curveCatalog",
                "title": "Curve Catalog",
                "settings": {"showCoverage": True},
            },
            "evidence-coverage": {
                "type": "evidenceCoverage",
                "title": "Evidence Coverage",
                "settings": {"compact": True},
            },
            "log-widget": {
                "type": "logWidget",
                "title": "Borehole Log",
                "tracks": [
                    {"id": "depth", "type": "depthAxis", "title": "Depth", "visible": True, "width": 70},
                    {
                        "id": "lithology",
                        "type": "lithology",
                        "title": "Lithology",
                        "visible": True,
                        "width": 180,
                    },
                    {"id": "seam", "type": "seam", "title": "Seam", "visible": True, "width": 90},
                    {
                        "id": "core-images",
                        "type": "images",
                        "title": "Core Images",
                        "visible": True,
                        "width": 170,
                    },
                    {
                        "id": "recovery",
                        "type": "quantitativeBar",
                        "title": "Recovery",
                        "visible": True,
                        "width": 110,
                        "valueField": "recovery_percent",
                        "unit": "%",
                        "min": 0,
                        "max": 100,
                        "color": "#55b7aa",
                    },
                    {
                        "id": "rqd",
                        "type": "quantitativeBar",
                        "title": "RQD",
                        "visible": True,
                        "width": 100,
                        "valueField": "rqd",
                        "unit": "%",
                        "min": 0,
                        "max": 100,
                        "valueMultiplier": 100,
                        "color": "#55b7aa",
                    },
                    {
                        "id": "curves",
                        "type": "curve",
                        "title": "Curves",
                        "visible": True,
                        "width": 260,
                        "curves": [],
                    },
                    {
                        "id": "remarks",
                        "type": "remarks",
                        "title": "Remarks",
                        "visible": True,
                        "width": 220,
                    },
                    {
                        "id": "ai-suggestions",
                        "type": "aiSuggestions",
                        "title": "AI",
                        "visible": True,
                        "width": 120,
                    },
                ],
            }
        },
    }
